#配置mybatis和mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias  #tlias是数据库名字
    username: root
    password: password
  data:
    redis:
      host:localhost
      port:6379

#mybatis日志
mybatis:
  configuration:
    #开启驼峰密码和下划线命名的自动转换
    map-underscore-to-camel-case: true
    #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug